services:
  webhook:
    image: ghcr.io/linuxserver-labs/webhook:latest
    container_name: webhook
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - EXTRA_PARAM=-hotreload #optional
    volumes:
      - ./config:/config
    ports:
      - 9000:9000
    restart: unless-stopped