services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config  # update this to your path
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped

  obsidian-couchdb:
    container_name: obsidian-couchdb
    image: couchdb:latest
    environment:
      - COUCHDB_USER=username  # update this
      - COUCHDB_PASSWORD=password  # update this
    volumes:
      - /path/to/data:/opt/couchdb/data
      - /path/to/etc/local.d:/opt/couchdb/etc/local.d
    ports:
      - "5984:5984"
    restart: unless-stopped