services:
  photoprism:
    image: photoprism/photoprism:arm64
    platform: "linux/arm64"
    container_name: photoprism
    ## Don't enable automatic restarts until PhotoPrism has been properly configured and tested!
    # restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - photoprismdb
    ports:
      - "2342:2342"
    ## Before you start the service, please check the following config options:
    ## https://docs.photoprism.app/getting-started/config-options/
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"  # Change this password
      # PHOTOPRISM_DISABLE_TLS: "false"
      PHOTOPRISM_DEFAULT_TLS: "true"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_HTTP_COMPRESSION: "none"
      PHOTOPRISM_WORKERS: 2
      PHOTOPRISM_READONLY: "true"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_INDEX_SCHEDULE: "" 
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "photoprismdb:3306"
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"  # Change this password
      ## Run as a non-root user after initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
      # PHOTOPRISM_UID: 1000
      # PHOTOPRISM_GID: 1000
    working_dir: "/photoprism"
    volumes:
      - "./test/photoprism/originals:/photoprism/originals"  # Modify this path to desired location
      - "./test/photoprism/storage:/photoprism/storage"  # Modify this path to desired location

  photoprismdb:
    image: lscr.io/linuxserver/mariadb
    platform: "linux/arm64"
    container_name: photoprismdb
    restart: unless-stopped
    stop_grace_period: 5s
    environment:
      TZ: Europe/London
      MYSQL_DATABASE: "photoprism"
      MYSQL_USER: "photoprism"
      MYSQL_PASSWORD: "insecure"  # Change this password
      MYSQL_ROOT_PASSWORD: "insecure"  # Change this password
    volumes:
      - "./test/photoprismdb:/config"  # Modify this path to desired location
